In [1]:
import pandas as pd

In [2]:
data = {
    "Employee_id" : [1,2,3,4],
    "Department" : ["HR","IT","IT","Marketing"],
    "City" : ["New york","Paris","New York","Tokyo"]
    
}

In [3]:
df = pd.DataFrame(data)

In [4]:
df

   Employee_id Department      City
0            1         HR  New york
1            2         IT     Paris
2            3         IT  New York
3            4  Marketing     Tokyo

In [13]:
encode_df = pd.get_dummies(df,columns=["Department","City"],drop_first = False ,dtype = int)

In [14]:
encode_df

,Employee_id,Department_HR,Department_IT,Department_Marketing,City_New York,City_New york,City_Paris,City_Tokyo
0,1,1,0,0,0,1,0,0
1,2,0,1,0,0,0,1,0
2,3,0,1,0,1,0,0,0
3,4,0,0,1,0,0,0,1